### PR TITLE
Maven project template with pom.xml

### PR DESCRIPTION
**Pull request by crazyne55**
I made sure to include all the latest files of the repository, excluding the `.idea` folder. Also I modified the `.gitignore` a bit.

### CODE REVIEW

**Comment by MichaelAndrew22** [comment]
Good job Alistar! 

Seems fine to my amateur understanding haha, nice. 

Sorry to hear that you felt disconnected from the group by the way Alistar,
hopefully that'll change as we understand more about what we are learning etc.
Also picking the right time to talk in class is key, it's hard to listen to you when i'm trying to listen
to the teacher at the same time haha.

We should really do the reading / studying about the main part of this class: the book 'Head First Design Patterns' or we'll probably become overwhelmed. There are also tutorials on youtube that cover the patterns such as this one (the Observer pattern we went over today): https://www.youtube.com/watch?v=-oLDJ2dbadA

Lastly we can download the sample code from the book here that has code for all the patterns: https://wickedlysmart.com/head-first-design-patterns/

**Comment by Cxrdary** [comment]
You've only committed to your own main fork so far, you must make a feature branch in intelliJ then commit and push that, then create a pull request within github.

**Comment by MichaelAndrew22** [comment]
I think that the main branch has now been overridden. Has it not?
We should be able to just use this project as the base now.
So as far as I know nows the time to make a dev branch.
And I might be mistaken but from now on we should make our own feature branches and merge them into the dev branch right?

**Comment by MichaelAndrew22** [comment]
Hey Guys Last thing i'm going to post tonight, I think he got the API's mixed up.

Pi4J seems a lot easier to implement, I don't understand dpiozeros led strip code at all.

Check out: https://pi4j.com/examples/components/ledstrip/
& https://github.com/Pi4J/pi4j-example-components/blob/main/src/main/java/com/pi4j/catalog/applications/LedStrip_App.java

to see how easy it is to interact with.

**Pull request merged**
